name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v1

      - name: Display secrets
        run: |
          echo "HOST: ${{ secrets.HOST }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "PORT: ${{ secrets.PORT }}"
          echo "PORT: ${{ secrets.WX }}"


      # - name: multiple command
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       whoami
      #       ls -al

      # - name: Deploy in prod
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       git pull
      #       sh 1_run.sh
